### ISSUE TITLE
.innerHTML

### ISSUE THREAD

**Issue by TheKevSter35** [CountNick/web-app-from-scratch-1920#11]
i see you are using .innerhtml  try using a template engine 
https://github.com/CountNick/web-app-from-scratch-1920/blob/222ed4f5f3f5a06d3dc14af7355639028d584d26/js/app.js#L87

**Comment by CountNick** [comment]
I switched it back to insertAdjecentHTML and nested template literals in this. I think i will keep it like this for now. But thanks for the advice!
