### ISSUE TITLE
peer feedback 2: diagrams

### ISSUE THREAD

**Issue by ReiniervanLimpt** [CountNick/web-app-from-scratch-1920#13]
**Actor diagram**: 

- right now you have a "DOM" module which serves to cleanup the current html displayed i gues??? this functionality could be part of your render module...
- Maybe you can add a "data" module to cleanup your json data (if needed)  and to set the data into local storage. 
- In your render module you have a function called searchCharacters(), this would be another function you could use in a "data" module.

Nice and clean diagram!!

**Interaction diagram**:

- On initializing the app you instantly check your local storage database, what for?? You could check the router first to check which hash is requested and let the application check if the required data is present in localstorage. 
- under **render** you call two functions while in this state you only want to render one and then render the other after the userinput.

**Comment by CountNick** [comment]
Thanks for the advice man! 🤡 I added your tips to the readme: [project](https://github.com/CountNick/web-app-from-scratch-1920)
